name: Pokedesk Backend

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      AI_API_KEY: ${{ secrets.AI_API_KEY }}

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          pip install -r requirement.txt

      - name: Run test
        run: |
          pytest -v


     

      - name: Login to Docker Hub
        run:  |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name:  Build Docker Image
        run: |
          docker build -t sumitduwal904/pokedesk .

      - name: Push docker image
        run:  |
          docker push sumitduwal904/pokedesk